# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Source\AdNDP\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 900))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/atom.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(500, 200))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.informationTextEdit = QtWidgets.QTextEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.informationTextEdit.sizePolicy().hasHeightForWidth())
        self.informationTextEdit.setSizePolicy(sizePolicy)
        self.informationTextEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.informationTextEdit.setObjectName("informationTextEdit")
        self.horizontalLayout.addWidget(self.informationTextEdit)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logTextEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.logTextEdit.setObjectName("logTextEdit")
        self.verticalLayout_2.addWidget(self.logTextEdit)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.resultTextEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.resultTextEdit.setObjectName("resultTextEdit")
        self.horizontalLayout_3.addWidget(self.resultTextEdit)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 18))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setEnabled(True)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.openFileAct = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/open.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openFileAct.setIcon(icon1)
        self.openFileAct.setObjectName("openFileAct")
        self.exportFileAct = QtWidgets.QAction(MainWindow)
        self.exportFileAct.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/save.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportFileAct.setIcon(icon2)
        self.exportFileAct.setObjectName("exportFileAct")
        self.clearScreenAct = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/clear.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearScreenAct.setIcon(icon3)
        self.clearScreenAct.setObjectName("clearScreenAct")
        self.startAnalysisAct = QtWidgets.QAction(MainWindow)
        self.startAnalysisAct.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/start.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startAnalysisAct.setIcon(icon4)
        self.startAnalysisAct.setObjectName("startAnalysisAct")
        self.aboutAct = QtWidgets.QAction(MainWindow)
        self.aboutAct.setIcon(icon)
        self.aboutAct.setObjectName("aboutAct")
        self.settingAct = QtWidgets.QAction(MainWindow)
        self.settingAct.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/setting.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingAct.setIcon(icon5)
        self.settingAct.setObjectName("settingAct")
        self.menuFile.addAction(self.openFileAct)
        self.menuFile.addAction(self.exportFileAct)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.clearScreenAct)
        self.menuSetting.addAction(self.settingAct)
        self.menuHelp.addAction(self.aboutAct)
        self.menu.addAction(self.startAnalysisAct)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.openFileAct)
        self.toolBar.addAction(self.startAnalysisAct)
        self.toolBar.addAction(self.clearScreenAct)
        self.toolBar.addAction(self.exportFileAct)
        self.toolBar.addAction(self.settingAct)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AdNDP"))
        self.groupBox.setTitle(_translate("MainWindow", "基本信息"))
        self.groupBox_2.setTitle(_translate("MainWindow", "分析日志"))
        self.groupBox_3.setTitle(_translate("MainWindow", "分析结果"))
        self.menuFile.setTitle(_translate("MainWindow", "文件"))
        self.menuSetting.setTitle(_translate("MainWindow", "设置"))
        self.menuHelp.setTitle(_translate("MainWindow", "帮助"))
        self.menu.setTitle(_translate("MainWindow", "分析"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.openFileAct.setText(_translate("MainWindow", "打开"))
        self.exportFileAct.setText(_translate("MainWindow", "导出"))
        self.clearScreenAct.setText(_translate("MainWindow", "清除"))
        self.startAnalysisAct.setText(_translate("MainWindow", "开始分析"))
        self.aboutAct.setText(_translate("MainWindow", "关于"))
        self.settingAct.setText(_translate("MainWindow", "设置"))
